// <auto-generated />
using System;
using LearningProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningProject.Migrations
{
    [DbContext(typeof(LearningProjectContext))]
    [Migration("20251120134446_AddIsDraftInCereri")]
    partial class AddIsDraftInCereri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimRoluri", b =>
                {
                    b.Property<int>("ClaimsIdClaim")
                        .HasColumnType("int");

                    b.Property<int>("RolesIdRol")
                        .HasColumnType("int");

                    b.HasKey("ClaimsIdClaim", "RolesIdRol");

                    b.HasIndex("RolesIdRol");

                    b.ToTable("ClaimRoluri");
                });

            modelBuilder.Entity("LearningProject.Models.CerereFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CereriId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CereriId");

                    b.ToTable("CerereFile");
                });

            modelBuilder.Entity("LearningProject.Models.Cereri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldCereriId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDraft")
                        .HasColumnType("bit");

                    b.Property<double>("value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("OldCereriId");

                    b.ToTable("Cereri");
                });

            modelBuilder.Entity("LearningProject.Models.Claim", b =>
                {
                    b.Property<int>("IdClaim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClaim"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClaim");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("LearningProject.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LearningProject.Models.Departamente", b =>
                {
                    b.Property<int>("id_departamente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_departamente"));

                    b.Property<string>("Denumire_departament")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("data_dezactivare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_inceput")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("id_departamente");

                    b.ToTable("Departamente");
                });

            modelBuilder.Entity("LearningProject.Models.DraftModel.CerereDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CerereDrafts");
                });

            modelBuilder.Entity("LearningProject.Models.DraftModel.CerereFileDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CerereDraftId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CerereDraftId");

                    b.ToTable("CerereFileDrafts");
                });

            modelBuilder.Entity("LearningProject.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("LearningProject.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOccurred")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("LearningProject.Models.Roluri", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Denumire_rol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdRol");

                    b.ToTable("Roluri");
                });

            modelBuilder.Entity("LearningProject.Models.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CerereId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimCanSignId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataSemnarii")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SignByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CerereId");

                    b.HasIndex("ClaimCanSignId");

                    b.HasIndex("SignByUserId");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("LearningProject.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstMidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LearningProject.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("data_dezactivare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_departament")
                        .HasColumnType("int");

                    b.Property<int>("roluriID")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("id_departament");

                    b.HasIndex("roluriID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("LearningProject.Models.V_employees", b =>
                {
                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Activity");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Department");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Manager");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.ToTable((string)null);

                    b.ToView("V_employees", (string)null);
                });

            modelBuilder.Entity("ClaimRoluri", b =>
                {
                    b.HasOne("LearningProject.Models.Claim", null)
                        .WithMany()
                        .HasForeignKey("ClaimsIdClaim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningProject.Models.Roluri", null)
                        .WithMany()
                        .HasForeignKey("RolesIdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearningProject.Models.CerereFile", b =>
                {
                    b.HasOne("LearningProject.Models.Cereri", "Cerere")
                        .WithMany("Files")
                        .HasForeignKey("CereriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cerere");
                });

            modelBuilder.Entity("LearningProject.Models.Cereri", b =>
                {
                    b.HasOne("LearningProject.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningProject.Models.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LearningProject.Models.Cereri", "OldCereri")
                        .WithMany()
                        .HasForeignKey("OldCereriId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedBy");

                    b.Navigation("OldCereri");
                });

            modelBuilder.Entity("LearningProject.Models.DraftModel.CerereFileDraft", b =>
                {
                    b.HasOne("LearningProject.Models.DraftModel.CerereDraft", null)
                        .WithMany("Files")
                        .HasForeignKey("CerereDraftId");
                });

            modelBuilder.Entity("LearningProject.Models.Enrollment", b =>
                {
                    b.HasOne("LearningProject.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningProject.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearningProject.Models.Signature", b =>
                {
                    b.HasOne("LearningProject.Models.Cereri", "Cerere")
                        .WithMany("Documente")
                        .HasForeignKey("CerereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningProject.Models.Claim", "ClaimCanSign")
                        .WithMany()
                        .HasForeignKey("ClaimCanSignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningProject.Models.User", "SignByUser")
                        .WithMany("DocumenteSemnate")
                        .HasForeignKey("SignByUserId");

                    b.Navigation("Cerere");

                    b.Navigation("ClaimCanSign");

                    b.Navigation("SignByUser");
                });

            modelBuilder.Entity("LearningProject.Models.User", b =>
                {
                    b.HasOne("LearningProject.Models.Departamente", "Departamente")
                        .WithMany()
                        .HasForeignKey("id_departament")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LearningProject.Models.Roluri", "roluri")
                        .WithMany("Users")
                        .HasForeignKey("roluriID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamente");

                    b.Navigation("roluri");
                });

            modelBuilder.Entity("LearningProject.Models.Cereri", b =>
                {
                    b.Navigation("Documente");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("LearningProject.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("LearningProject.Models.DraftModel.CerereDraft", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("LearningProject.Models.Roluri", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LearningProject.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("LearningProject.Models.User", b =>
                {
                    b.Navigation("DocumenteSemnate");
                });
#pragma warning restore 612, 618
        }
    }
}
