// <auto-generated />
using System;
using LearningProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningProject.Migrations
{
    [DbContext(typeof(LearningProjectContext))]
    [Migration("20251103065403_Modify Departament-User")]
    partial class ModifyDepartamentUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimRoluri", b =>
                {
                    b.Property<int>("ClaimsIdClaim")
                        .HasColumnType("int");

                    b.Property<int>("RolesIdRol")
                        .HasColumnType("int");

                    b.HasKey("ClaimsIdClaim", "RolesIdRol");

                    b.HasIndex("RolesIdRol");

                    b.ToTable("ClaimRoluri");
                });

            modelBuilder.Entity("LearningProject.Models.Claim", b =>
                {
                    b.Property<int>("IdClaim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClaim"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClaim");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("LearningProject.Models.Departamente", b =>
                {
                    b.Property<int>("id_departamente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_departamente"));

                    b.Property<string>("Denumire_departament")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("data_dezactivare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_inceput")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("id_departamente");

                    b.ToTable("Departamente");
                });

            modelBuilder.Entity("LearningProject.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOccurred")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("LearningProject.Models.Roluri", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Denumire_rol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdRol");

                    b.ToTable("Roluri");
                });

            modelBuilder.Entity("LearningProject.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("data_dezactivare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_departament")
                        .HasColumnType("int");

                    b.Property<int>("roluriID")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("id_departament");

                    b.HasIndex("roluriID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ClaimRoluri", b =>
                {
                    b.HasOne("LearningProject.Models.Claim", null)
                        .WithMany()
                        .HasForeignKey("ClaimsIdClaim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningProject.Models.Roluri", null)
                        .WithMany()
                        .HasForeignKey("RolesIdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearningProject.Models.User", b =>
                {
                    b.HasOne("LearningProject.Models.Departamente", "Departamente")
                        .WithMany()
                        .HasForeignKey("id_departament")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningProject.Models.Roluri", "roluri")
                        .WithMany("Users")
                        .HasForeignKey("roluriID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamente");

                    b.Navigation("roluri");
                });

            modelBuilder.Entity("LearningProject.Models.Roluri", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
